version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_network
    volumes:
      - /home/tmdgy6232/nginx.conf:/etc/nginx/nginx.conf
      - gis_static:/data/static/
      - gis_media:/data/media/

  django:
    image: gis_django:4
    networks:
      - gis_network
    volumes:
      - gis_static:/home/gis_2/staticfiles/
      - gis_media:/home/gis_2/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234

networks:
  gis_network:

volumes:
  gis_static:
  gis_media:
  gis_mariadb: